/* ISPs Contract Managers */
INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'ISP CM 1', 'Brazil', 'isp.cm1.brazil@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '0x93d0D2b299865C488e6C2ff6BF0B39e1BdB63422', NULL, 'PT', 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'ISP CM 2', 'Brazil', 'isp.cm2.brazil@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'PT', 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'ISP CM 1', 'Botswana', 'isp.cm1.botswana@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BW'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '0x7D680C1E21b7360aB5Cc89aDe494BDA91Dd69be9', NULL, 'EN', 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'ISP CM 2', 'Botswana', 'isp.cm2.botswana@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BW'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'EN', 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');


/* ISPs Customer Service Agents */
INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'ISP Serv. Agent 1', 'Brazil', 'isp.sa1.brazil@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'PT' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'ISP Serv. Agent 2', 'Brazil', 'isp.sa2.brazil@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'PT' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'ISP Serv. Agent 1', 'Botswana', 'isp.sa1.botswana@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BW'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'EN' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'ISP Serv. Agent 2', 'Botswana', 'isp.sa2.botswana@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BW'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'EN' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');


/* Country Contract Creators */
INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'CC 1', 'Brazil', 'cc1.brazil@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'PT' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'CC 2', 'Brazil', 'cc2.brazil@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'PT' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'CC 1', 'Botswana', 'cc1.botswana@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BW'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'EN' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'CC 2', 'Botswana', 'cc2.botswana@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BW'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'EN' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');


/* Country Accountants */
INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'CA 1', 'Brazil', 'ca1.brazil@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'PT' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'CA 2', 'Brazil', 'ca2.brazil@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'PT' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'CA 1', 'Botswana', 'ca1.botswana@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BW'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'EN' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'CA 2', 'Botswana', 'ca2.botswana@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BW'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'EN' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');


/* Country Super Admins */
INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'C. Admin 1', 'Brazil', 'admin1.brazil@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'PT' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'C. Admin 1', 'Botswana', 'admin1.botswana@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BW'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'EN' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

/* Country Monitors */
INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'Monitor 1', 'Brazil', 'monitor1.brazil@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'PT' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'Monitor 1', 'Botswana', 'monitor1.botswana@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BW'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'EN' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');


/* School Connectivity Managers */
INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'SCH Manager 1', 'Brazil', 'sch.manager1.brazil@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'PT' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'SCH Manager 2', 'Brazil', 'sch.manager2.brazil@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'PT' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'SCH Manager 3', 'Brazil', 'sch.manager3.brazil@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BR'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'PT' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'SCH Manager 1', 'Botswana', 'sch.manager1.botswana@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BW'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'EN' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'SCH Manager 2', 'Botswana', 'sch.manager2.botswana@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BW'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'EN' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');

INSERT INTO public.users (id, name, last_name, email, password, country_id, created_at, updated_at, wallet_address, wallet_request_string, default_language, about, address, zip_code, phone_number, photo_url) 
VALUES (nextval('users_id_seq'), 'SCH Manager 3', 'Botswana', 'sch.manager3.botswana@giga.com', '$argon2id$v=19$t=3,m=4096,p=1$UATswoa8reg2n214IJF32g$7UeFUIhnAQn+VbrLo6en1K0JDc0bR8vG0wnxDqXU4Ns', (select id from countries where code = 'BW'), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL, NULL, 'EN' , 'something about me', '90210 Broadway Blvd', '94116', '+40 777666555', 'https://i.ibb.co/GVV63pf/avatar-default.jpg');


INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'isp.cm1.brazil@giga.com'), (select id from roles where code = 'ISP.CONTRACT.MANAGER') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'isp.cm2.brazil@giga.com'), (select id from roles where code = 'ISP.CONTRACT.MANAGER') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'isp.cm1.botswana@giga.com'), (select id from roles where code = 'ISP.CONTRACT.MANAGER') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'isp.cm2.botswana@giga.com'), (select id from roles where code = 'ISP.CONTRACT.MANAGER') , CURRENT_TIMESTAMP, NULL);

INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'isp.sa1.brazil@giga.com'), (select id from roles where code = 'ISP.CUSTOMER.SERVICE') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'isp.sa2.brazil@giga.com'), (select id from roles where code = 'ISP.CUSTOMER.SERVICE') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'isp.sa1.botswana@giga.com'), (select id from roles where code = 'ISP.CUSTOMER.SERVICE') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'isp.sa2.botswana@giga.com'), (select id from roles where code = 'ISP.CUSTOMER.SERVICE') , CURRENT_TIMESTAMP, NULL);

INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'cc1.brazil@giga.com'), (select id from roles where code = 'COUNTRY.CONTRACT.CREATOR') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'cc2.brazil@giga.com'), (select id from roles where code = 'COUNTRY.CONTRACT.CREATOR') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'cc1.botswana@giga.com'), (select id from roles where code = 'COUNTRY.CONTRACT.CREATOR') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'cc2.botswana@giga.com'), (select id from roles where code = 'COUNTRY.CONTRACT.CREATOR') , CURRENT_TIMESTAMP, NULL);

INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'ca1.brazil@giga.com'), (select id from roles where code = 'COUNTRY.ACCOUNTANT') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'ca2.brazil@giga.com'), (select id from roles where code = 'COUNTRY.ACCOUNTANT') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'ca1.botswana@giga.com'), (select id from roles where code = 'COUNTRY.ACCOUNTANT') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'ca2.botswana@giga.com'), (select id from roles where code = 'COUNTRY.ACCOUNTANT') , CURRENT_TIMESTAMP, NULL);

INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'admin1.brazil@giga.com'), (select id from roles where code = 'COUNTRY.SUPER.ADMIN') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'admin1.botswana@giga.com'), (select id from roles where code = 'COUNTRY.SUPER.ADMIN') , CURRENT_TIMESTAMP, NULL);

INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'monitor1.brazil@giga.com'), (select id from roles where code = 'COUNTRY.MONITOR') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'monitor1.botswana@giga.com'), (select id from roles where code = 'COUNTRY.MONITOR') , CURRENT_TIMESTAMP, NULL);

INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'sch.manager1.brazil@giga.com'), (select id from roles where code = 'SCHOOL.CONNECTIVITY.MANAGER') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'sch.manager2.brazil@giga.com'), (select id from roles where code = 'SCHOOL.CONNECTIVITY.MANAGER') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'sch.manager3.brazil@giga.com'), (select id from roles where code = 'SCHOOL.CONNECTIVITY.MANAGER') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'sch.manager1.botswana@giga.com'), (select id from roles where code = 'SCHOOL.CONNECTIVITY.MANAGER') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'sch.manager2.botswana@giga.com'), (select id from roles where code = 'SCHOOL.CONNECTIVITY.MANAGER') , CURRENT_TIMESTAMP, NULL);
INSERT INTO public.user_roles (id, user_id, role_id, created_at, updated_at) 
VALUES (nextval('user_roles_id_seq'), (select id from users where email = 'sch.manager3.botswana@giga.com'), (select id from roles where code = 'SCHOOL.CONNECTIVITY.MANAGER') , CURRENT_TIMESTAMP, NULL);

insert into public.isp_users (id, user_id, isp_id, created_at, updated_at) select nextval('isp_users_id_seq'), u.id, (select id from isps where upper(name) ='VIVO'), CURRENT_TIMESTAMP, null from users u where name like '%ISP%' and email like '%brazil%';
insert into public.isp_users (id, user_id, isp_id, created_at, updated_at) select nextval('isp_users_id_seq'), u.id, (select id from isps where upper(name) ='AT&T BOTSWANA'), CURRENT_TIMESTAMP, null from users u where name like '%ISP%' and email like '%botswana%';

insert into school_users (id, user_id, school_id, created_at, updated_at) values(nextval('school_users_id_seq'), (select id from users where email = 'sch.manager1.brazil@giga.com'), (select id from schools where external_id = '24002798'), CURRENT_TIMESTAMP, null);
insert into school_users (id, user_id, school_id, created_at, updated_at) values(nextval('school_users_id_seq'), (select id from users where email = 'sch.manager2.brazil@giga.com'), (select id from schools where external_id = '43092721'), CURRENT_TIMESTAMP, null);
insert into school_users (id, user_id, school_id, created_at, updated_at) values(nextval('school_users_id_seq'), (select id from users where email = 'sch.manager3.brazil@giga.com'), (select id from schools where external_id = '43093213'), CURRENT_TIMESTAMP, null);

INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), true, '8412140', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2022-05-10 01:35:57-03', '2022-08-20 01:35:57.001-03', 3, 3, 3, '2023-04-30 01:35:57.003-03', '2023-04-30 01:35:57.003-03', '2023-04-30 01:35:57.003-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), true, '8412141', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2021-03-09 01:35:57.076-03', '2021-09-06 01:35:57.076-03', 3, 3, 5, '2023-04-30 01:35:57.077-03', '2023-04-30 01:35:57.077-03', '2023-04-30 01:35:57.077-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), true, '8412142', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2020-03-11 01:35:57.113-03', '2020-10-13 01:35:57.114-03', 3, 3, 5, '2023-04-30 01:35:57.116-03', '2023-04-30 01:35:57.116-03', '2023-04-30 01:35:57.116-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), false, '7287574', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2021-03-01 01:35:57.139-03', '2021-09-30 01:35:57.139-03', 8, 3, 5, '2023-04-30 01:35:57.14-03', '2023-04-30 01:35:57.14-03', '2023-04-30 01:35:57.14-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), false, '7287575', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2020-03-02 01:35:57.166-03', '2020-10-23 01:35:57.166-03', 8, 3, 5, '2023-04-30 01:35:57.168-03', '2023-04-30 01:35:57.168-03', '2023-04-30 01:35:57.168-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), false, '7287576', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2019-10-25 01:35:57.208-03', '2020-07-10 01:35:57.208-03', 8, 3, 5, '2023-04-30 01:35:57.21-03', '2023-04-30 01:35:57.21-03', '2023-04-30 01:35:57.21-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), false, '4949780', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2022-11-13 01:35:57.248-03', '2023-07-12 01:35:57.248-03', 2, 3, 5, '2023-04-30 01:35:57.249-03', '2023-04-30 01:35:57.249-03', '2023-04-30 01:35:57.249-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), false, '5079401', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2022-11-16 01:35:57.257-03', '2023-07-05 01:35:57.257-03', 2, 3, 2, '2023-04-30 01:35:57.258-03', '2023-04-30 01:35:57.258-03', '2023-04-30 01:35:57.258-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), false, '6934334', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2022-04-13 01:35:57.266-03', '2022-08-20 01:35:57.266-03', 10, 3, 3, '2023-04-30 01:35:57.267-03', '2023-04-30 01:35:57.267-03', '2023-04-30 01:35:57.267-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), true, '9020161', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2022-04-09 01:35:57.297-03', '2022-11-10 01:35:57.297-03', 11, 3, 3, '2023-04-30 01:35:57.298-03', '2023-04-30 01:35:57.298-03', '2023-04-30 01:35:57.298-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), false, '5631506', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2022-06-15 01:35:57.327-03', '2022-10-12 01:35:57.327-03', 6, 3, 3, '2023-04-30 01:35:57.328-03', '2023-04-30 01:35:57.328-03', '2023-04-30 01:35:57.328-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), false, '2526207', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2022-10-01 01:35:57.353-03', '2023-01-18 01:35:57.353-03', 2, 3, 3, '2023-04-30 01:35:57.354-03', '2023-04-30 01:35:57.354-03', '2023-04-30 01:35:57.354-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), true, '2154531', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2021-12-16 01:35:57.383-03', '2022-07-01 01:35:57.383-03', 5, 3, 4, '2023-04-30 01:35:57.384-03', '2023-04-30 01:35:57.384-03', '2023-04-30 01:35:57.384-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), false, '6483012', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2021-12-31 01:35:57.41-03', '2022-03-14 01:35:57.41-03', 9, 3, 4, '2023-04-30 01:35:57.412-03', '2023-04-30 01:35:57.412-03', '2023-04-30 01:35:57.412-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), true, '2364146', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2021-04-04 01:35:57.438-03', '2021-09-06 01:35:57.438-03', 8, 3, 5, '2023-04-30 01:35:57.439-03', '2023-04-30 01:35:57.439-03', '2023-04-30 01:35:57.439-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), true, '1089794', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2020-03-27 01:35:57.466-03', '2020-10-13 01:35:57.466-03', 11, 3, 5, '2023-04-30 01:35:57.467-03', '2023-04-30 01:35:57.467-03', '2023-04-30 01:35:57.467-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, created_at, updated_at, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BR'), false, '5804450', (select id from currencies where code = 'BRL'), 1000000.00, 1, '2021-04-22 01:35:57.479-03', '2021-07-30 01:35:57.479-03', 12, 3, 5, '2023-04-30 01:35:57.48-03', '2023-04-30 01:35:57.48-03', '2023-04-30 01:35:57.48-03');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BW'), false, 'BotswanaMeasures1', (select id from currencies where code = 'USD'), 35000.00, 4, '2023-01-01 00:00:00.000 -0600', '2023-12-31 00:00:00.000 -0600', 15, 1, 4, '2023-01-01 00:00:00.000 -0600');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BW'), false, 'BotswanaMeasures2', (select id from currencies where code = 'USD'), 35000.00, 4, '2023-01-01 00:00:00.000 -0600', '2023-12-31 00:00:00.000 -0600', 15, 1, 4, '2023-01-01 00:00:00.000 -0600');
INSERT INTO public.contracts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, status, launch_date) VALUES (nextval('contracts_id_seq'), (select id from countries where code = 'BW'), false, 'BotswanaMeasures3', (select id from currencies where code = 'USD'), 35000.00, 4, '2023-01-01 00:00:00.000 -0600', '2023-12-31 00:00:00.000 -0600', 15, 1, 4, '2023-01-01 00:00:00.000 -0600');

INSERT INTO public.drafts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, schools, expected_metrics, created_at, updated_at, launch_date) VALUES (nextval('drafts_id_seq'), (select id from countries where code = 'BR'), true, 'D9393487', (SELECT id from currencies where code = 'BRL'), 1000, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP+ INTERVAL '90 days', (select id from isps where upper(name) = 'VIVO'), 1, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  CURRENT_TIMESTAMP+ INTERVAL '10 days');
INSERT INTO public.drafts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, schools, expected_metrics, created_at, updated_at, launch_date) VALUES (nextval('drafts_id_seq'), (select id from countries where code = 'BR'), true, 'D1233333', (SELECT id from currencies where code = 'BRL'), 1000, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP+ INTERVAL '60 days', (select id from isps where upper(name) = 'VIVO'), 1, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  CURRENT_TIMESTAMP+ INTERVAL '10 days');
INSERT INTO public.drafts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, schools, expected_metrics, created_at, updated_at, launch_date) VALUES (nextval('drafts_id_seq'), (select id from countries where code = 'BR'), true, 'DTESTTEST11', (SELECT id from currencies where code = 'BRL'), 1000, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP+ INTERVAL '70 days', (select id from isps where upper(name) = 'VIVO'), 1, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  CURRENT_TIMESTAMP+ INTERVAL '10 days');
INSERT INTO public.drafts (id, country_id, government_behalf, name, currency_id, budget, frequency_id, start_date, end_date, isp_id, created_by, schools, expected_metrics, created_at, updated_at, launch_date, automatic) VALUES (nextval('drafts_id_seq'), (select id from countries where code = 'BR'), true, 'DTESTTEST22', (SELECT id from currencies where code = 'BRL'), 1000, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP+ INTERVAL '70 days', (select id from isps where upper(name) = 'VIVO'), 1, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  CURRENT_TIMESTAMP+ INTERVAL '10 days', true);


INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '24002798'), 1, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '43092721'), 1, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '43093213'), 1, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '22001166'), 1, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '43093388'), 1, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '26056313'), 2, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '41058348'), 2, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '42015758'), 2, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '43093248'), 2, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '43181163'), 2, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '22030131'), 3, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '41066561'), 3, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '41017943'), 3, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '22025146'), 3, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '41025890'), 3, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '51033534'), 4, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '51049490'), 4, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '43092829'), 4, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '43092659'), 4, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '43092900'), 4, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '51018900'), 5, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '26052563'), 5, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '26052628'), 5, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '41068696'), 5, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '26052644'), 5, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '42131138'), 6, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '42114659'), 6, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '29214831'), 6, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '31009563'), 6, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '51019752'), 6, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '22030034'), 7, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '22029753'), 7, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '22000429'), 7, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '42023815'), 7, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '24002615'), 7, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '41044126'), 8, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '51002795'), 8, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '31000576'), 8, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '42017696'), 8, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '51008912'), 8, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '41103572'), 13, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '26034085'), 13, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '35376553'), 13, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '41099940'), 13, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '41145712'), 13, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '42143128'), 14, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '43050166'), 14, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '41107012'), 14, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '41141091'), 14, 10000.00);
INSERT INTO public.school_contracts (id, school_id, contract_id, budget) VALUES (nextval('school_contracts_id_seq'), (select id from schools where external_id = '41356047'), 14, 10000.00);

INSERT INTO public.expected_metrics (id, contract_id, metric_id, value, created_at, updated_at) select nextval('expected_metrics_id_seq'), id, 1, FLOOR(random() * (100 - 2 + 1) + 2) as random, CURRENT_TIMESTAMP, NULL from contracts;
INSERT INTO public.expected_metrics (id, contract_id, metric_id, value, created_at, updated_at) select nextval('expected_metrics_id_seq'), id, 2, FLOOR(random() * (100 - 2 + 1) + 2) as random, CURRENT_TIMESTAMP, NULL from contracts;
INSERT INTO public.expected_metrics (id, contract_id, metric_id, value, created_at, updated_at) select nextval('expected_metrics_id_seq'), id, 3, FLOOR(random() * (100 - 2 + 1) + 2) as random, CURRENT_TIMESTAMP, NULL from contracts;
INSERT INTO public.expected_metrics (id, contract_id, metric_id, value, created_at, updated_at) select nextval('expected_metrics_id_seq'), id, 4, FLOOR(random() * (100 - 2 + 1) + 2) as random, CURRENT_TIMESTAMP, NULL from contracts;

insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 1, 3, 1, '2023-06-29 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 2, 3, 1, '2023-06-29 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 3, 3, 1, '2023-06-29 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 4, 3, 1, '2023-06-29 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 1, 3, 1, '2023-06-30 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 2, 3, 1, '2023-06-30 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 3, 3, 1, '2023-06-30 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 4, 3, 1, '2023-06-30 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 1, 3, 1, '2023-07-29 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 2, 3, 1, '2023-07-29 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 3, 3, 1, '2023-07-29 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 4, 3, 1, '2023-07-29 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 1, 3, 1, '2023-07-30 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 2, 3, 1, '2023-07-30 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 3, 3, 1, '2023-07-30 13:47:55.610 -0600', 1);
insert into public.measures (id, metric_id, value, school_id, created_at, contract_id) values(nextval('measures_id_seq'), 4, 3, 1, '2023-07-30 13:47:55.610 -0600', 1);

INSERT INTO public.payments (id, date_from, date_to, invoice_id, receipt_id, is_verified, contract_id, paid_by, amount, currency_id, created_at, updated_at, description, status, created_by, metrics) VALUES (nextval('payments_id_seq'), CURRENT_TIMESTAMP, '2022-05-01 02:59:59.999+00', NULL, NULL, false, 9, NULL, 123, (select id from currencies where code = 'BRL'), '2023-05-05 09:47:33.847+00', '2023-05-05 09:47:33.847+00', '', 2, 1, '{"connectionsMedian": [], "withoutConnection": 100, "allEqualOrAboveAvg": 0, "atLeastOneBellowAvg": 0}');
INSERT INTO public.payments (id, date_from, date_to, invoice_id, receipt_id, is_verified, contract_id, paid_by, amount, currency_id, created_at, updated_at, description, status, created_by, metrics) VALUES (nextval('payments_id_seq'), CURRENT_TIMESTAMP, '2022-07-01 02:59:59.999+00', NULL, NULL, false, 9, NULL, 2222, (select id from currencies where code = 'BRL'), '2023-05-05 10:10:21.56+00', '2023-05-05 10:10:21.56+00', '222', 2, 1, '{"connectionsMedian": [], "withoutConnection": 100, "allEqualOrAboveAvg": 0, "atLeastOneBellowAvg": 0}');
INSERT INTO public.payments (id, date_from, date_to, invoice_id, receipt_id, is_verified, contract_id, paid_by, amount, currency_id, created_at, updated_at, description, status, created_by, metrics) VALUES (nextval('payments_id_seq'), CURRENT_TIMESTAMP, '2022-06-01 02:59:59.999+00', NULL, NULL, false, 9, NULL, 222, (select id from currencies where code = 'BRL'), '2023-05-05 10:11:59.487+00', '2023-05-05 10:11:59.487+00', '23232', 2, 1, '{"connectionsMedian": [], "withoutConnection": 100, "allEqualOrAboveAvg": 0, "atLeastOneBellowAvg": 0}');
INSERT INTO public.payments (id, date_from, date_to, invoice_id, receipt_id, is_verified, contract_id, paid_by, amount, currency_id, created_at, updated_at, description, status, created_by, metrics) VALUES (nextval('payments_id_seq'), CURRENT_TIMESTAMP, '2022-01-01 02:59:59.999+00', NULL, NULL, false, 13, NULL, 2, (select id from currencies where code = 'BRL'), '2023-06-06 20:48:59.285+00', '2023-06-06 20:49:40.472+00', 'test', 2, 3, '{"connectionsMedian": [], "withoutConnection": 100, "allEqualOrAboveAvg": 0, "atLeastOneBellowAvg": 0}');
INSERT INTO public.payments (id, date_from, date_to, invoice_id, receipt_id, is_verified, contract_id, paid_by, amount, currency_id, created_at, updated_at, description, status, created_by, metrics) VALUES (nextval('payments_id_seq'), CURRENT_TIMESTAMP, '2022-01-01 02:59:59.999+00', NULL, NULL, false, 13, NULL, 2, (select id from currencies where code = 'BRL'), '2023-06-06 20:48:59.285+00', '2023-06-06 20:49:40.472+00', 'test2', 1, 3, '{"connectionsMedian": [], "withoutConnection": 100, "allEqualOrAboveAvg": 0, "atLeastOneBellowAvg": 0}');
